---
type: Secret
api_version: secrets/v1
metadata:
  name: slack_webhook_url
spec:
  provider: vault
  id: secret/sensu/slack#webhook_url
---
type: Secret
api_version: secrets/v1
metadata:
  name: slack_channel
spec:
  provider: vault
  id: secret/sensu/slack#channel
---
type: Asset
api_version: core/v2
metadata:
  name: sensu/sensu-slack-handler:1.4.0
  annotations:
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu/sensu-slack-handler
    io.sensu.bonsai.name: sensu-slack-handler
    io.sensu.bonsai.namespace: sensu
    io.sensu.bonsai.tags: ""
    io.sensu.bonsai.tier: Supported
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu/sensu-slack-handler
    io.sensu.bonsai.version: 1.4.0
spec:
  builds:
    - url: https://assets.bonsai.sensu.io/6c615e79bc0445b2decdfbb593b5a5a4a2d3e07f/sensu-slack-handler_1.4.0_windows_amd64.tar.gz
      sha512: 520fd6171797888d2fcdcd5b1ccbfb1b282baf709f2c29bcdaad4817966c74b2a4ecdff2bec46088b846d074b3457612c7f2250f250d0a75f87c6605d21d72c4
      filters:
        - entity.system.os == 'windows'
        - entity.system.arch == 'amd64'
    - url: https://assets.bonsai.sensu.io/6c615e79bc0445b2decdfbb593b5a5a4a2d3e07f/sensu-slack-handler_1.4.0_darwin_amd64.tar.gz
      sha512: 1d6e92cbc845ff2a66ef9b2c241e8e3d0c4e4af021ffcb29d19b11356e5d7a592cbcc7d39a657957f0b89ce0b66f16520d02840b61174ed37a2b95d416bf83b0
      filters:
        - entity.system.os == 'darwin'
        - entity.system.arch == 'amd64'
    - url: https://assets.bonsai.sensu.io/6c615e79bc0445b2decdfbb593b5a5a4a2d3e07f/sensu-slack-handler_1.4.0_linux_armv7.tar.gz
      sha512: 4c2f9f50ca112ef31572e53446b100dd483cb8ad143643490033725a809545e95465d977308bf42f816d18a09a29335f7865d032d96d6e633be17c7c8c5efe1f
      filters:
        - entity.system.os == 'linux'
        - entity.system.arch == 'armv7'
    - url: https://assets.bonsai.sensu.io/6c615e79bc0445b2decdfbb593b5a5a4a2d3e07f/sensu-slack-handler_1.4.0_linux_arm64.tar.gz
      sha512: 559859a95e4cc37b8c4749be9ef443b7ddf76743a3ae4ac7e91eb1ebc3b79395a26b05012b0e90efbbef50efd7b5484d7a42db11967cfae1ab4d85d6e0ecd257
      filters:
        - entity.system.os == 'linux'
        - entity.system.arch == 'arm64'
    - url: https://assets.bonsai.sensu.io/6c615e79bc0445b2decdfbb593b5a5a4a2d3e07f/sensu-slack-handler_1.4.0_linux_386.tar.gz
      sha512: ab75a249fc7522c8ae4fe4100313674c95b0014613a837817d1a455d87d754242fc7c2105b84c96581ac5d1402a01401e5c6444e66fc702bfcfb81929eb1bca0
      filters:
        - entity.system.os == 'linux'
        - entity.system.arch == '386'
    - url: https://assets.bonsai.sensu.io/6c615e79bc0445b2decdfbb593b5a5a4a2d3e07f/sensu-slack-handler_1.4.0_linux_amd64.tar.gz
      sha512: 3ccedc2b5ca400e0fe9b4425fc5503e68dfb4066b1886b0bf960ba0b725eddbbe1132de8ab4c3cf5a787220ee81a793e8eb41858424ab57f368f9ccfdd07f8b1
      filters:
        - entity.system.os == 'linux'
        - entity.system.arch == 'amd64'
