#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
    CREATE USER ${SENSU_BACKEND_CLUSTER_ADMIN_USERNAME} WITH ENCRYPTED PASSWORD '${SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD}';
    CREATE DATABASE sensu_events;
    GRANT ALL PRIVILEGES ON DATABASE sensu_events TO ${SENSU_BACKEND_CLUSTER_ADMIN_USERNAME};
EOSQL