#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username ${POSTGRES_USER} --dbname "${POSTGRES_DB}" <<-EOSQL
    CREATE USER ${MATTERMOST_DB_USER} WITH ENCRYPTED PASSWORD '${MATTERMOST_DB_PASSWORD}';
    CREATE DATABASE ${MATTERMOST_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${MATTERMOST_DB} TO ${MATTERMOST_DB_USER};
EOSQL