#!/bin/sh

USERS_RBAC=${1:-"config/sensu/rbac"}
SENSU_API_URL=${SENSU_API_URL:-"http://sensu-backend:8080"}
SENSU_NAMESPACE=${SENSU_NAMESPACE:-"default"}

check_deps() {
  for DEP in sensuctl jq
  do
    command -v ${DEP} > /dev/null 2>&1
    if [ $? -ne 0 ]; then
      echo "Missing required dependency: \"${DEP}\""
      exit 127
    fi
  done
}

validate_io() {
  if [ ! -d ${USERS_RBAC} ]; then
    echo "Missing or invalid user RBAC resources: \"${USERS_RBAC}\" (must be a directory)"
    exit 2
  fi
  if [ ! -d ${SENSU_WORKSHOP_SEEDS} ]; then
    echo "Missing or invalid namespace seed resources: \"${SENSU_WORKSHOP_SEEDS}\" (must be a directory)"
    exit 2
  fi
}

validate_api_url() {
  curl -XGET ${SENSU_API_URL}/health > /dev/null 2>&1
  if [ $? -ne 0 ]; then
    echo "No Sensu API found at ${SENSU_API_URL}"
    exit 2
  fi
}

create_user_accounts() {
  /usr/local/bin/sensuctl create -r -f ${USERS_RBAC}
  if [ $? -ne 0 ]; then
    echo "Error encountered while creating workshop user accounts"
    exit 2
  else
    echo "Successfully created the following workshop user accounts:"
    echo
    sensuctl namespace list --format tabular
  fi
}

echo "Creating Sensu user accounts..."
wait-for-sensuctl
if [ $? -gt 0 ]; then
  echo "Failed to create Sensu user accounts."
  exit 2
fi
check_deps && \
validate_io && \
validate_api_url && \
create_user_accounts
if [ $? -gt 0 ]; then
  echo "Failed to create Sensu user accounts."
  exit 2
fi
echo ""
exit 0
