#!/bin/sh

#
# inetOrgPerson Attribute Ref: https://ldapwiki.com/wiki/InetOrgPerson
#
# > /dev/null 2>&1
# displayName: $USER_FULLNAME
# userPassword: $USER_PASSWORD

USER_ID="bjones"
USER_FULLNAME="Bob Jones"
USER_EMAIL="bjones@example.com"
USER_PASSWORD="test"


echo "Start seeding ldap users"


echo "Add a user $USER_FULLNAME"
ldapdelete -H ldaps://openldap -D cn=admin,$OPENLDAP_ORG_DN -w $OPENLDAP_ADMIN_PASSWORD "cn=$USER_ID,ou=Users,$OPENLDAP_ORG_DN"
ret=$?
if [ $ret -ne 0 ] && [ $ret -ne 32 ]; then
 echo "ldapdelete user Bad Return Value : $ret"
 exit $ret
fi
ldapadd -H ldaps://openldap -D cn=admin,$OPENLDAP_ORG_DN -w $OPENLDAP_ADMIN_PASSWORD << EOF 
dn: cn=$USER_ID,ou=Users,$OPENLDAP_ORG_DN
cn: $USER_ID
sn: $USER_FULLNAME
mail: $USER_EMAIL
uid: $USER_ID
userPassword: $USER_PASSWORD
objectClass: inetOrgPerson
EOF
ret=$?
if [ $ret -ne 0 ] && [ $ret -ne 68 ]; then
 echo "ldapadd user Bad Return Value : $ret"
 exit $ret
fi

echo "Verifying user $USER_FULLNAME password"
ldapwhoami -H ldaps://openldap -D cn=$USER_ID,ou=Users,$OPENLDAP_ORG_DN -w $USER_PASSWORD
ret=$?
if [ $ret -ne 0 ]; then
 echo "ldapwhoami simple bind Bad Return Value : $ret"
 exit $ret
fi



echo  "Add user $USER_FULLNAME to engineering group"
ldapadd -H ldaps://openldap -D cn=admin,$OPENLDAP_ORG_DN -w $OPENLDAP_ADMIN_PASSWORD << EOF
dn: cn=engineering,ou=Users,$OPENLDAP_ORG_DN
changetype: modify
add: member
member: cn=$USER_ID,ou=Users,$OPENLDAP_ORG_DN
EOF
ret=$?
if [ $ret -ne 0 ] && [ $ret -ne 20 ]; then
 echo "ldapadd user to group Bad Return Value : $ret"
 exit $ret
fi



echo "Done seeding ldap users"
