#!/usr/bin/env sh

SENSU_API_URL=${SENSU_API_URL:-"http://sensu-backend:8080"}
SENSU_BACKEND_CLUSTER_ADMIN_USERNAME=${SENSU_BACKEND_CLUSTER_ADMIN_USERNAME:-"sensu"}
SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD=${SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD:-"sensu"}
SENSU_BACKEND_CLUSTER_ADMIN_API_KEY=${SENSU_BACKEND_CLUSTER_ADMIN_API_KEY}
SENSU_NAMESPACE=${SENSU_NAMESPACE:-"default"}
SENSU_ETCD_CLIENT_URLS=${SENSU_ETCD_CLIENT_URLS}
SENSU_INIT_TEMP_FILE="/root/.sensu-backend-init"
INTERVAL=2
RETRIES=5
ATTEMPT=0
SUCCESS=0

sensu_backend_init() {
  echo "Initializing the Sensu backend..."
  if [ ! -z ${SENSU_ETCD_CLIENT_URLS} ]; then
    sensu-backend init --etcd-client-urls ${SENSU_ETCD_CLIENT_URLS} --cluster-admin-username ${SENSU_BACKEND_CLUSTER_ADMIN_USERNAME} --cluster-admin-password ${SENSU_BACKEND_CLUSTER_ADMIN_USERNAME} --cluster-admin-api-key ${SENSU_BACKEND_CLUSTER_ADMIN_API_KEY} --ignore-already-initialized
    if [ $? -eq 0 ]; then
      echo "Successfully initialized the Sensu backend!"
      echo ""
      return 0
    else
      echo "Failed to initialize the Sensu backend!"
      echo ""
      return 1
    fi
  fi
}

wait_for_sensu_backend() {
  while [ ${ATTEMPT} -lt ${RETRIES} ]; do
    curl ${SENSU_API_URL}/health > /dev/null 2>&1
    if [ $? -eq 0 ]; then
      SUCCESS=$(expr ${SUCCESS} + 1)
      break
    fi
    echo "Unable to connect to ${SENSU_API_URL}, retrying in ${INTERVAL} seconds..."
    sleep ${INTERVAL}
    ATTEMPT=$(expr ${ATTEMPT} + 1)
  done

  if [ $SUCCESS -eq 0 ]; then
    echo "Failed to connect to ${SENSU_API_URL} after ${RETRIES} attempts; giving up."
    exit 2
  fi

  if [ $ATTEMPT -gt 0 ] && [ $SUCCESS -gt 0 ]; then
    # only display success message if we don't connect on the first try
    echo "Successfully connected to ${SENSU_API_URL}"
    touch ${SENSU_INIT_TEMP_FILE}
  fi
}

sensu_backend_init
if [ $? -gt 0 ]; then
  echo "Failed to initialize the sensu-backend!"
  echo ""
  exit 2
fi
wait_for_sensu_backend
exec $@
exit 0